epi_dev_admin:
    path: /admin
    defaults:
      _controller: EpiDevAdminBundle:Default:index

app:
    path: /default
    defaults:
      _controller: AppBundle:Default:index

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#AdminBundle
actuality:
    path: /admin/actuality
    defaults:
      _controller: EpiDevAdminBundle:Actuality:actuality
modifyActuality:
    path: /admin/modifyActuality
    defaults:
      _controller: EpiDevAdminBundle:Actuality:modifyActuality
saveActuality:
    path: /admin/saveActuality
    defaults:
      _controller: EpiDevAdminBundle:Actuality:saveActuality
addActuality:
    path: /admin/addActuality
    defaults:
      _controller: EpiDevAdminBundle:Actuality:addActuality
uploadActuality:
    path: /admin/uploadActuality
    defaults:
      _controller: EpiDevAdminBundle:Actuality:uploadActuality
deleteActuality:
    path: /admin/deleteActuality
    defaults:
      _controller: EpiDevAdminBundle:Actuality:deleteActuality
duplicateActuality:
    path: /admin/duplicateActuality
    defaults:
      _controller: EpiDevAdminBundle:Actuality:duplicateActuality

cms:
  path: /admin/cms
  defaults:
    _controller: EpiDevAdminBundle:CMS:cms
modifyCms:
  path: /admin/modifyCms
  defaults:
    _controller: EpiDevAdminBundle:CMS:modifyCms
saveCms:
  path: /admin/saveCms
  defaults:
    _controller: EpiDevAdminBundle:CMS:saveCms


agency:
    path: /admin/agency
    defaults:
      _controller: EpiDevAdminBundle:Agency:agency
upload_agency:
    path: /admin/upload_agency
    defaults:
      _controller: EpiDevAdminBundle:Agency:upload
add_agency:
    path: /admin/add_agency
    defaults:
      _controller: EpiDevAdminBundle:Agency:add
edit_agency:
  path: /admin/edit_agency
  defaults:
    _controller: EpiDevAdminBundle:Agency:edit
duplicate_agency:
  path: /admin/duplicate_agency
  defaults:
    _controller: EpiDevAdminBundle:Agency:duplicate
delete_agency:
  path: /admin/delete_agency
  defaults:
    _controller: EpiDevAdminBundle:Agency:delete
save_agency:
  path: /admin/save_agency
  defaults:
    _controller: EpiDevAdminBundle:Agency:save

offer:
    path: /admin/offer
    defaults:
      _controller: EpiDevAdminBundle:Offer:offer
add_offer:
  path: /admin/add_offer
  defaults:
    _controller: EpiDevAdminBundle:Offer:add
upload_offer:
  path: /admin/upload_offer
  defaults:
    _controller: EpiDevAdminBundle:Offer:upload
edit_offer:
  path: /admin/edit_offer
  defaults:
    _controller: EpiDevAdminBundle:Offer:edit
duplicate_offer:
  path: /admin/duplicate_offer
  defaults:
    _controller: EpiDevAdminBundle:Offer:duplicate
delete_offer:
  path: /admin/delete_offer
  defaults:
    _controller: EpiDevAdminBundle:Offer:delete
save_offer:
  path: /admin/save_offer
  defaults:
    _controller: EpiDevAdminBundle:Offer:save

job:
    path: /admin/job
    defaults:
      _controller: EpiDevAdminBundle:Job:job
add_job:
  path: /admin/add_job
  defaults:
    _controller: EpiDevAdminBundle:Job:add_job
add_domain:
  path: /admin/add_domain
  defaults:
    _controller: EpiDevAdminBundle:Job:add_domain
upload_job:
  path: /admin/upload_job
  defaults:
    _controller: EpiDevAdminBundle:Job:upload_job
upload_domain:
  path: /admin/upload_domain
  defaults:
    _controller: EpiDevAdminBundle:Job:upload_domain
edit_job:
  path: /admin/edit_job
  defaults:
    _controller: EpiDevAdminBundle:Job:edit_job
edit_domain:
  path: /admin/edit_domain
  defaults:
    _controller: EpiDevAdminBundle:Job:edit_domain
delete_job:
  path: /admin/delete_job
  defaults:
    _controller: EpiDevAdminBundle:Job:delete_job
delete_domain:
  path: /admin/delete_domain
  defaults:
    _controller: EpiDevAdminBundle:Job:delete_domain
save_job:
  path: /admin/save_job
  defaults:
    _controller: EpiDevAdminBundle:Job:save_job
save_domain:
  path: /admin/save_domain
  defaults:
    _controller: EpiDevAdminBundle:Job:save_domain

application:
  path: /admin/application
  defaults:
    _controller: EpiDevAdminBundle:Application:view
add_application:
  path: /admin/add_application
  defaults:
    _controller: EpiDevAdminBundle:Application:add
edit_application:
  path: /admin/edit_application
  defaults:
    _controller: EpiDevAdminBundle:Application:edit
duplicate_application:
  path: /admin/duplicate_application
  defaults:
    _controller: EpiDevAdminBundle:Application:duplicate
delete_application:
  path: /admin/delete_application
  defaults:
    _controller: EpiDevAdminBundle:Application:delete

candidate:
  path: /admin/candidate
  defaults:
    _controller: EpiDevAdminBundle:Candidate:index
edit_candidate:
  path: /admin/edit_candidate
  defaults:
    _controller: EpiDevAdminBundle:Candidate:edit
duplicate_candidate:
  path: /admin/duplicate_candidate
  defaults:
    _controller: EpiDevAdminBundle:Candidate:duplicate
delete_candidate:
  path: /admin/delete_candidate
  defaults:
    _controller: EpiDevAdminBundle:Candidate:delete
add_candidate:
  path: /admin/add/candidate
  defaults:
    _controller: EpiDevAdminBundle:Candidate:add
get_cv_admin:
  path: /admin/add/get_cv_admin
  defaults:
    _controller: EpiDevAdminBundle:Candidate:get_cv_admin
upload_candidate:
  path: /admin/upload/candidate
  defaults:
    _controller: EpiDevAdminBundle:Candidate:upload
candidate_cv_upload:
  path: /admin/upload/cv_upload
  defaults:
    _controller: EpiDevAdminBundle:Candidate:cv_upload
update_candidate:
  path: /admin/update/candidate
  defaults:
    _controller: EpiDevAdminBundle:Candidate:update

monthly_worker:
  path: /admin/monthly_worker
  defaults:
    _controller: EpiDevAdminBundle:Monthly_worker:list
modifyWorker:
    path: /admin/modifyWorker
    defaults:
      _controller: EpiDevAdminBundle:Monthly_worker:modifyWorker
saveWorker:
    path: /admin/saveWorker
    defaults:
      _controller: EpiDevAdminBundle:Monthly_worker:saveWorker
addWorker:
    path: /admin/addWorker
    defaults:
      _controller: EpiDevAdminBundle:Monthly_worker:addWorker
uploadWorker:
    path: /admin/uploadWorker
    defaults:
      _controller: EpiDevAdminBundle:Monthly_worker:uploadWorker
deleteWorker:
    path: /admin/deleteWorker
    defaults:
      _controller: EpiDevAdminBundle:Monthly_worker:deleteWorker
duplicateWorker:
    path: /admin/duplicateWorker
    defaults:
      _controller: EpiDevAdminBundle:Monthly_worker:duplicateWorker
# Public

home:
    path: /
    defaults:
      _controller: AppBundle:Home:index

list_offers:
    path: /list_offers
    defaults:
      _controller: AppBundle:Offerfront:list
inc_i_offer:
    path: /inc_i_offer
    defaults:
      _controller: AppBundle:Offerfront:inc_i_offer

offer_details:
    path: /offer_details
    defaults:
      _controller: AppBundle:Offerfront:details

list_actuality:
    path: /actuality
    defaults:
      _controller: AppBundle:Actualityfront:list

actuality_details:
  path: /actuality_details
  defaults:
    _controller: AppBundle:Actualityfront:details

contact:
    path: /contact
    defaults:
      _controller: AppBundle:Contactfront:index
sendEmail:
    path: /sendEmail
    defaults:
      _controller: AppBundle:Contactfront:sendEmail

spontaneous_application:
    path: /spontaneous_application
    defaults:
      _controller: AppBundle:Applicationfront:index

apply_offer:
  path: /apply_offer
  defaults:
    _controller: AppBundle:Applicationfront:apply_offer

personnal_space:
    path: /personnal_space
    defaults:
      _controller: AppBundle:Accountfront:personnal_space

set_alert:
    path: /set_alert
    defaults:
      _controller: AppBundle:Accountfront:set_alert

delete_alert:
    path: /delete_alert
    defaults:
        _controller: AppBundle:Accountfront:delete_alert

login_register:
    path: /login.html
    defaults:
        _controller: AppBundle:Accountfront:login_register

lost_password:
    path: /lost_password.html
    defaults:
        _controller: AppBundle:Accountfront:lost_password

my_informations:
    path: /my_informations
    defaults:
        _controller: AppBundle:Accountfront:my_informations

get_cv:
    path: /get_cv
    defaults:
      _controller: AppBundle:Accountfront:get_CV

upload_cv:
    path: /upload_cv
    defaults:
      _controller: AppBundle:Accountfront:upload_cv

register_cv_upload:
    path: /register/cv/upload
    defaults:
      _controller: AppBundle:Accountfront:register_cv_upload

modify_cv:
    path: /modify/cv
    defaults:
      _controller: AppBundle:Accountfront:modify_cv

information_modify:
    path: /modify_info
    defaults:
        _controller: AppBundle:Accountfront:modify_info

update_info:
    path: /update_info
    defaults:
      _controller: AppBundle:Accountfront:update_info

my_alerts:
    path: /my_alerts
    defaults:
        _controller: AppBundle:Accountfront:my_alerts

get_city:
  path: /get_city
  defaults:
    _controller: AppBundle:Redirecting:get_city

variable_url_cms:
  path: /{path}
  defaults:
    _controller: AppBundle:VariableUrlCms:variableUrlCms

# Redirect
remove_trailing_slash:
    path: /{url}
    defaults:
      _controller: AppBundle:Redirecting:removeTrailingSlash
    requirements:
        url: .*/$
    methods: [GET]
