epi_dev_admin:
    path: /admin
    defaults:
      _controller: EpiDevAdminBundle:Default:index

app:
    path: /default
    defaults:
      _controller: AppBundle:Default:index

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#AdminBundle
actuality:
    path: /admin/actuality
    defaults:
      _controller: EpiDevAdminBundle:Admin:actuality
modifyActuality:
    path: /admin/modifyActuality
    defaults:
      _controller: EpiDevAdminBundle:Actuality:modifyActuality
saveActuality:
    path: /admin/saveActuality
    defaults:
      _controller: EpiDevAdminBundle:Actuality:saveActuality

cms:
  path: /admin/cms
  defaults:
    _controller: EpiDevAdminBundle:Admin:cms
modifyCMS:
  path: /admin/modifyCMS
  defaults:
    _controller: EpiDevAdminBundle:CMS:modifyCMS
saveCMS:
  path: /admin/saveCMS
  defaults:
    _controller: EpiDevAdminBundle:CMS:saveCMS


agency:
    path: /admin/agency
    defaults:
      _controller: EpiDevAdminBundle:Agency:agency
add_agency:
    path: /admin/add/agency
    defaults:
      _controller: EpiDevAdminBundle:Agency:add

offer:
    path: /admin/offer
    defaults:
      _controller: EpiDevAdminBundle:Offer:offer
add_offer:
  path: /admin/add_offer
  defaults:
    _controller: EpiDevAdminBundle:Offer:add
edit_offer:
  path: /admin/edit_offer
  defaults:
    _controller: EpiDevAdminBundle:Offer:edit
duplicate_offer:
  path: /admin/duplicate_offer
  defaults:
    _controller: EpiDevAdminBundle:Offer:duplicate
delete_offer:
  path: /admin/delete_offer
  defaults:
    _controller: EpiDevAdminBundle:Offer:delete

application:
  path: /admin/application
  defaults:
    _controller: EpiDevAdminBundle:Application:view
add_application:
  path: /admin/add_application
  defaults:
    _controller: EpiDevAdminBundle:Application:add
edit_application:
  path: /admin/edit_application
  defaults:
    _controller: EpiDevAdminBundle:Application:edit
duplicate_application:
  path: /admin/duplicate_application
  defaults:
    _controller: EpiDevAdminBundle:Application:duplicate
delete_application:
  path: /admin/delete_application
  defaults:
    _controller: EpiDevAdminBundle:Application:delete

# Public

home:
    path: /
    defaults:
      _controller: AppBundle:Home:index

recruteurs:
  path: /recruteurs
  defaults:
    _controller: AppBundle:Recruteursfront:recruteurs

list_offers:
    path: /list_offers
    defaults:
      _controller: AppBundle:Offerfront:list

offer_details:
    path: /offer_details
    defaults:
      _controller: AppBundle:Offerfront:details

list_actuality:
    path: /list_actuality
    defaults:
      _controller: AppBundle:Actualityfront:list

contact:
    path: /contact
    defaults:
      _controller: AppBundle:Contactfront:index

spontaneous_application:
    path: /spontaneous_application
    defaults:
      _controller: AppBundle:Applicationfront:index

personnal_space:
    path: /personnal_space
    defaults:
      _controller: AppBundle:Accountfront:personnal_space

login_register:
    path: /login.html
    defaults:
        _controller: AppBundle:Accountfront:login_register

lost_password:
    path: /lost_password.html
    defaults:
        _controller: AppBundle:Accountfront:lost_password

my_informations:
    path: /my_informations
    defaults:
        _controller: AppBundle:Accountfront:my_informations

information_modify:
    path: /modify_info
    defaults:
        _controller: AppBundle:Accountfront:modify_info

my_alerts:
    path: /my_alerts
    defaults:
        _controller: AppBundle:Accountfront:my_alerts
