epi_dev_admin:
    path: /admin
    defaults:
      _controller: EpiDevAdminBundle:Default:index

home:
    path: /
    defaults:
      _controller: AppBundle:Default:index

app:
    path: /default
    defaults:
      _controller: AppBundle:Default:index

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#AdminBundle
actuality:
    path: /admin/actuality
    defaults:
      _controller: EpiDevAdminBundle:Admin:actuality

modifyActuality:
    path: /admin/modify
    defaults:
      _controller: EpiDevAdminBundle:Actuality:modify

saveActuality:
    path: /admin/saveActuality
    defaults:
      _controller: EpiDevAdminBundle:Actuality:saveActuality

agency:
    path: /admin/agency
    defaults:
      _controller: EpiDevAdminBundle:Agency:agency

add_agency:
    path: /admin/add/agency
    defaults:
      _controller: EpiDevAdminBundle:Agency:add
offer:
    path: /admin/offer
    defaults:
      _controller: EpiDevAdminBundle:Offer:offer
