<?php

namespace EpiDev\AdminBundle\Repository;

/**
 * MonthlyWorkerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonthlyWorkerRepository extends \Doctrine\ORM\EntityRepository
{
}
